export const penalCode = [
  ['01 · Desacato à autoridade', 'Ofender, provocar, humilhar ou desrespeitar policiais, agentes públicos ou funcionários em serviço. Pena: 20 min de prisão ou multa de R$ 1.000.'],
  ['02 · Desobediência', 'Recusar-se a cumprir uma ordem legal dada por uma autoridade. Pena: 20 min de prisão ou multa de R$ 1.500.'],
  ['03 · Perturbação da ordem pública', 'Gritaria, confusão, algazarra, buzina indevida, bloqueio de vias ou atrapalhar o RP. Pena: 20 min de prisão ou multa de R$ 1.000.'],
  ['04 · Falsa comunicação de crime', 'Acionar a polícia ou abrir denúncia falsa para prejudicar alguém ou atrapalhar o RP. Pena: 25 min de prisão ou multa de R$ 2.000.'],
  ['05 · Ocultação de identidade', 'Usar máscara em locais públicos, durante abordagem ou situação suspeita sem justificativa. Pena: 20 min de prisão ou multa de R$ 1.500.'],
  ['06 · Direção perigosa', 'Alta velocidade, contramão, calçadas, atropelamento por imprudência ou risco a civis. Pena: 25 min de prisão ou multa de R$ 2.500.'],
  ['07 · Fuga de abordagem', 'Ignorar parada, fugir de blitz ou viatura, ou abandonar veículo para evitar abordagem. Pena: 35 min de prisão ou multa de R$ 4.000.'],
  ['08 · Atropelamento culposo', 'Atropelar sem intenção clara de matar, por imprudência ou negligência. Pena: 30 min de prisão ou multa de R$ 3.000.'],
  ['09 · Atropelamento doloso', 'Usar veículo como arma para ferir ou matar intencionalmente. Pena: 50 min de prisão ou multa de R$ 7.000.'],
  ['10 · Veículo irregular', 'Conduzir veículo roubado, sem placa, abandonado, danificado propositalmente ou usado em crime. Pena: 25 min de prisão ou multa de R$ 2.500. O veículo pode ser apreendido.'],
  ['11 · Porte ilegal de arma', 'Portar arma sem licença, autorização ou justificativa válida. Pena: 35 min de prisão ou multa de R$ 5.000. A arma será apreendida.'],
  ['12 · Disparo em via pública', 'Efetuar disparos em cidade, local público ou próximo de civis sem motivo legítimo. Pena: 35 min de prisão ou multa de R$ 4.000.'],
  ['13 · Ameaça armada', 'Apontar arma, intimidar ou ameaçar cidadão ou autoridade. Pena: 40 min de prisão ou multa de R$ 5.000.'],
  ['14 · Posse de armamento pesado', 'Portar fuzis, explosivos, granadas, lançadores ou armas restritas sem autorização. Pena: 25 min de prisão ou multa de R$ 8.000. Armamento apreendido.'],
  ['15 · Agressão física', 'Atacar outro jogador com socos, armas brancas ou objetos sem causar morte. Pena: 25 min de prisão ou multa de R$ 2.500.'],
  ['16 · Tentativa de homicídio', 'Tentar matar outro jogador por arma, atropelamento ou explosivos. Pena: 40 min de prisão ou multa de R$ 8.000.'],
  ['17 · Homicídio', 'Matar outro jogador. Pena: 60 min de prisão ou multa de R$ 10.000.'],
  ['18 · Sequestro', 'Privar alguém de liberdade, levar a vítima contra a vontade ou mantê-la presa. Pena: 60 min de prisão ou multa de R$ 12.000.'],
  ['19 · Tortura ou maus-tratos', 'Machucar, humilhar, ameaçar repetidamente ou manter alguém em situação abusiva. Pena: 55 min de prisão ou multa de R$ 10.000.'],
  ['20 · Latrocínio', 'Roubo seguido de morte. Pena: 70 min de prisão ou multa de R$ 15.000.'],
  ['21 · Furto', 'Pegar item, veículo ou pertence sem ameaça ou violência. Pena: 25 min de prisão ou multa de R$ 13.000.'],
  ['22 · Roubo', 'Tomar bens usando ameaça, arma ou violência. Pena: 40 min de prisão ou multa de R$ 6.000.'],
  ['23 · Roubo de veículo', 'Roubar, arrombar ou tomar veículo alheio. Pena: 35 min de prisão ou multa de R$ 5.000. O veículo deve ser devolvido ou apreendido.'],
  ['24 · Invasão de propriedade', 'Entrar em casa, base, estabelecimento ou área privada sem permissão. Pena: 30 min de prisão ou multa de R$ 4.000.'],
  ['25 · Dano ao patrimônio', 'Destruir veículos, portas, construções, plantações, lojas ou itens de outro jogador. Pena: 35 min de prisão ou multa de R$ 5.000; pode haver indenização.'],
  ['27 · Tráfico de drogas ou bebidas ilícitas', 'Vender, transportar, produzir ou distribuir drogas. Pena: 35 min de prisão + multa de R$ 13.000.'],
  ['28 · Posse de itens roubados', 'Estar com itens de roubo, furto, sequestro ou ações criminosas. Pena: 35 min de prisão ou multa de R$ 5.000. Itens apreendidos.'],
  ['29 · Contrabando', 'Transportar ou vender armas, drogas, munições, explosivos ou itens ilegais em grande quantidade. Pena: 60 min de prisão ou multa de R$ 15.000.'],
  ['30 · Falsidade ideológica', 'Mentir nome, cargo, identidade, profissão ou se passar por outra pessoa. Pena: 30 min de prisão ou multa de R$ 3.500.'],
  ['31 · Falsificação de documentos', 'Criar, portar ou usar documentos, licenças ou autorizações falsos. Pena: 40 min de prisão ou multa de R$ 6.000.'],
  ['32 · Suborno', 'Oferecer dinheiro, itens ou vantagens para autoridade deixar de cumprir o dever. Pena: 45 min de prisão ou multa de R$ 8.000.'],
  ['33 · Corrupção', 'Autoridade aceitar suborno, liberar criminosos, vender informações ou abusar do cargo. Pena: 60 min de prisão ou multa de R$ 15.000; pode gerar exoneração.'],
  ['34 · Fuga da prisão', 'Escapar, tentar escapar ou ajudar outro preso a fugir. Pena: 50 min de prisão ou multa de R$ 8.000.'],
  ['35 · Obstrução de justiça', 'Atrapalhar investigação, esconder criminoso, destruir provas ou mentir em depoimento. Pena: 40 min de prisão ou multa de R$ 6.000.'],
  ['36 · Formação de quadrilha', 'Organizar ou participar de grupo criminoso. Pena: 20 min de prisão ou multa de R$ 15.000.'],
  ['37 · Assalto a estabelecimento', 'Assaltar loja, banco, fazenda, mineradora, posto ou estabelecimento do servidor. Pena: 60 min de prisão ou multa de R$ 12.000.'],
  ['38 · Ataque contra autoridade', 'Atirar, atropelar, emboscar ou tentar matar policiais ou agentes públicos. Pena: 70 min de prisão ou multa de R$ 18.000.'],
  ['39 · Terrorismo', 'Explodir locais públicos, causar massacre, ataques em massa ou ações que prejudiquem a cidade. Pena: 90 min de prisão ou multa de R$ 30.000; pode gerar punição administrativa.'],
  ['40 · Organização criminosa armada', 'Grupo armado que domina território, realiza assaltos, sequestros, tráfico ou ataques coordenados. Pena: 30 min de prisão ou multa de R$ 15.000; bens, armas e veículos podem ser apreendidos.']
]
